# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a808aa5a4db2a456f0fa404c8fdd47b1ebae6f3d7c0a176f0b9af3986599bc0b606e614c6968a1dc5341b6a6e268b9c35cbbb8912d9c7961084cc70f287df5d

test:
  secret_key_base: 6fc6dcee1de569279d64d241591ab980bc6bc818b9eaaeb94a106e72e7a17c35bfe41729a7e1e6e1f414f825bd98f481e45e5db350638d3ad9837250aa245c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
